# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-04 17:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('bi_an_hua', models.CharField(max_length=10)),
                ('ci_mu', models.CharField(max_length=10)),
                ('da_gou', models.CharField(max_length=10)),
                ('hua_niao', models.CharField(max_length=10)),
                ('huang', models.CharField(max_length=10)),
                ('huang_chuang', models.CharField(max_length=10)),
                ('hui_ye_ji', models.CharField(max_length=10)),
                ('jiu_tun', models.CharField(max_length=10)),
                ('qing_deng', models.CharField(max_length=10)),
                ('xiao_lu', models.CharField(max_length=10)),
                ('xue_tong_zi', models.CharField(max_length=10)),
                ('yan_mo', models.CharField(max_length=10)),
                ('yao_dao', models.CharField(max_length=10)),
                ('yi_mu', models.CharField(max_length=10)),
                ('yu_zao_qian', models.CharField(max_length=10)),
            ],
        ),
    ]
